# Generated by Django 2.1.15 on 2020-05-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='todos',
            field=models.ManyToManyField(blank=True, to='cms.Todo'),
        ),
    ]
