# Generated by Django 2.1.15 on 2020-05-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_user_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='todo',
            field=models.CharField(blank=True, max_length=50, verbose_name='ToDo'),
        ),
    ]
