# Generated by Django 2.1.15 on 2020-06-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_user_todos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'todo', 'verbose_name_plural': 'todos'},
        ),
    ]
