# Generated by Django 2.1.15 on 2020-05-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_user_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='todo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Todo'),
        ),
    ]
