# Generated by Django 2.1.15 on 2020-06-06 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20200606_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='main_todo',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='cms.Todo'),
        ),
    ]
