# Generated by Django 2.1.15 on 2020-05-25 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20200517_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Todo')),
                ('is_done', models.BooleanField(default=False, verbose_name='Todo')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='todo',
        ),
        migrations.AddField(
            model_name='todo',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
