# Generated by Django 2.1.15 on 2020-06-06 13:54

import cms.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20200606_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='main_todo',
            field=models.ForeignKey(blank=True, default=cms.models.get_or_create_do_nothing, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='owner', to='cms.Todo'),
        ),
    ]
